# Generated by Django 6.0.4 on 2026-04-27 02:21

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='useraccounts',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='role',
            field=models.CharField(choices=[('NOT_SELECTED', 'Not Selected'), ('SYSTEM_ADMINISTRATOR', 'System Administrator'), ('HR_MANAGER', 'HR Manager'), ('EMPLOYEE', 'Employee')], default='NOT_SELECTED', verbose_name='User Role'),
        ),
    ]
