# Generated by Django 6.0.4 on 2026-04-27 02:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the employee', max_length=255, verbose_name='Employee Name')),
                ('title', models.CharField(blank=True, help_text='The title of the employee', max_length=255, null=True, verbose_name='Employee Title')),
                ('hire_date', models.DateField(default=datetime.date.today)),
                ('mobile', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Employee Phone Number')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
    ]
